const sampleData = [
  {
    "idDrink": "17006",
    "strDrink": "Kool First Aid",
    "strDrinkAlternate": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Shot",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Shot glass",
    "strInstructions": "Add Kool Aid to a double shot glass, and top with rum. Slam and shoot.",
    "strInstructionsES": null,
    "strInstructionsDE": "Geben Sie Kool Aid in ein Doppelschnapsglas und füllen Sie es mit Rum. Knall und Schuss.",
    "strInstructionsFR": null,
    "strInstructionsIT": "Aggiungi Kool-Aid, successivamente aggiungi il rum.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/hfp6sv1503564824.jpg",
    "strIngredient1": "151 proof rum",
    "strIngredient2": "Kool-Aid",
    "strIngredient3": null,
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "2 oz light ",
    "strMeasure2": "1/2 tsp Tropical ",
    "strMeasure3": null,
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strImageSource": null,
    "strImageAttribution": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2017-08-24 09:53:44"
  },
  {
    "idDrink": "11113",
    "strDrink": "Bloody Mary",
    "strDrinkAlternate": null,
    "strTags": "IBA,ContemporaryClassic",
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": "Contemporary Classics",
    "strAlcoholic": "Alcoholic",
    "strGlass": "Old-fashioned glass",
    "strInstructions": "Stirring gently, pour all ingredients into highball glass. Garnish.",
    "strInstructionsES": null,
    "strInstructionsDE": "Unter leichtem Rühren alle Zutaten in ein Highball-Glas geben. Garnieren.",
    "strInstructionsFR": null,
    "strInstructionsIT": "Mescolando delicatamente, versare tutti gli ingredienti nel bicchiere highball.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/t6caa21582485702.jpg",
    "strIngredient1": "Vodka",
    "strIngredient2": "Tomato juice",
    "strIngredient3": "Lemon juice",
    "strIngredient4": "Worcestershire sauce",
    "strIngredient5": "Tabasco sauce",
    "strIngredient6": "Lime",
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1 1/2 oz ",
    "strMeasure2": "3 oz ",
    "strMeasure3": "1 dash ",
    "strMeasure4": "1/2 tsp ",
    "strMeasure5": "2-3 drops ",
    "strMeasure6": "1 wedge ",
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strImageSource": "https://www.thecocktaildb.com/drink/11113-Bloody-Mary",
    "strImageAttribution": "TheCocktialDB.com",
    "strCreativeCommonsConfirmed": "Yes",
    "dateModified": "2015-08-18 15:09:14"
  },
  {
    "idDrink": "11118",
    "strDrink": "Blue Margarita",
    "strDrinkAlternate": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Cocktail glass",
    "strInstructions": "Rub rim of cocktail glass with lime juice. Dip rim in coarse salt. Shake tequila, blue curacao, and lime juice with ice, strain into the salt-rimmed glass, and serve.",
    "strInstructionsES": null,
    "strInstructionsDE": "Den Rand des Cocktailglases mit Limettensaft einreiben. Den Rand in grobes Salz tauchen. Tequila, blauen Curacao und Limettensaft mit Eis schütteln, in das mit Salz umhüllte Glas abseihen und servieren.",
    "strInstructionsFR": null,
    "strInstructionsIT": "Strofinare il bordo del bicchiere da cocktail con succo di lime. Immergere il bordo nel sale grosso. Shakerare tequila, blue curacao e succo di lime con ghiaccio, filtrare nel bicchiere bordato di sale e servire.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/bry4qh1582751040.jpg",
    "strIngredient1": "Tequila",
    "strIngredient2": "Blue Curacao",
    "strIngredient3": "Lime juice",
    "strIngredient4": "Salt",
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1 1/2 oz ",
    "strMeasure2": "1 oz ",
    "strMeasure3": "1 oz ",
    "strMeasure4": "Coarse ",
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strImageSource": null,
    "strImageAttribution": null,
    "strCreativeCommonsConfirmed": "Yes",
    "dateModified": "2015-08-18 14:51:53"
  }
]

export default sampleData;